name = "qwik-dream-menu"
compatibility_date = "2022-07-25"
# Build the SSR code that will run in the Worker.
build.command = "npm run build"
# The SSR code is generated in the `server` directory.
main = "server/entry.ssr.js"
# The client code is generated in the `dist` directory.
# We use the `assets` config to supply these static files as needed.
assets = "./dist"
# Detected a Node builtin module import while Node compatibility is disabled.
# Add node_compat = true to your wrangler.toml file to enable Node compatibility.
node_compat = true